// Team roster for the video-call section. `photo` is null until real
// webcam-style headshots land — the UI falls back to an initials avatar.
// Swapping photos in is a data-only change: set `photo` to a path under
// /public (e.g. "/team/alex.jpg").
export const TEAM_ROSTER = [
  {
    id: "alex",
    name: "Alex Dawson",
    role: "Product Designer",
    initials: "AD",
    avatarColor: "#7c5cff",
    photo: "/videos/team/Alex.jpg",
    video: "/videos/team/Alex.mp4",
  },
  {
    id: "anton",
    name: "Anton Chinakov",
    role: "QA Manual Engineer",
    initials: "AC",
    avatarColor: "#cc6655",
    photo: "/videos/team/Anton.jpg",
    video: "/videos/team/Anton.mp4",
  },
  {
    id: "dmitry",
    name: "Dmitry Makarenko",
    role: "C++ Developer",
    initials: "DM",
    avatarColor: "#55aa88",
    photo: "/videos/team/Dmitry.jpg",
    video: "/videos/team/Dmitry.mp4",
  },
  {
    id: "elnur",
    name: "Elnur Ismailzada",
    role: "C++ Developer",
    initials: "EI",
    avatarColor: "#77aa66",
    photo: null,
  },
  {
    id: "gabriel",
    name: "Gabriel Sartori",
    role: "C++ Developer",
    initials: "GS",
    avatarColor: "#6688bb",
    photo: "/videos/team/Gabriel.jpg",
    video: "/videos/team/Gabriel.mp4",
  },
  {
    id: "grzegorz",
    name: "Grzegorz Wojciechowski",
    role: "C++ Developer",
    initials: "GW",
    avatarColor: "#aa6677",
    photo: "/videos/team/Grzegorz.jpg",
    video: "/videos/team/Grzegorz.mp4",
  },
  {
    id: "johan",
    name: "Johan Althoff",
    role: "Audacity Product Design",
    initials: "JA",
    avatarColor: "#5599aa",
    photo: null,
  },
  {
    id: "matthieu",
    name: "Matthieu Hodgkinson",
    role: "Senior Audio Developer",
    initials: "MH",
    avatarColor: "#bb8855",
    photo: "/videos/team/Matthieu.jpg",
    video: "/videos/team/Matthieu.mp4",
  },
  {
    id: "paul",
    name: "Paul Martin",
    role: "Audio Developer",
    initials: "PM",
    avatarColor: "#66aa99",
    photo: "/videos/team/Paul.jpg",
    video: "/videos/team/Paul.mp4",
  },
  {
    id: "sergey",
    name: "Sergey Lapysh",
    role: "QA Manual Engineer",
    initials: "SL",
    avatarColor: "#9966bb",
    photo: null,
  },
  {
    id: "yana",
    name: "Yana Larina",
    role: "Project Manager",
    initials: "YL",
    avatarColor: "#cc7788",
    photo: "/videos/team/Yana.jpg",
    video: "/videos/team/Yana.mp4",
  },
];
