// Generated by "bun run pull-campaigns" — do not edit. Source of truth is the Confluence promo calendar (see .env).
import type { PromoData } from "./types";

export const campaignBannerPromos: Record<string, PromoData> = {
  "80sDreamsBundle": {
    type: "banner",
    isActive: true,
    priority: 50,
    osTargets: ["Windows", "OS X"],
    startDate: "2026-06-11",
    endDate: "2026-06-25",
    message:
      "80s Dreams Bundle: The reverb and synth duo for retro-inspired sound. Create lush ambience and vintage tones.",
    tracking: {
      category: "Promo CTA",
      action: "Promo CTA button",
      name: "80s Dreams Bundle MuseHub",
    },
    cta: {
      text: "Get it on MuseHub",
      link: "https://www.musehub.com/bundle/80s-dreams-bundle?utm_source=au-web-banner&utm_medium=au-banner",
    },
  },
  denoiser: {
    type: "banner",
    isActive: true,
    priority: 50,
    osTargets: ["Windows", "OS X"],
    startDate: "2026-05-28",
    endDate: "2026-06-11",
    message:
      "Denoiser: The smart noise removal tool for clean audio. Detect, reduce, and restore sound without artifacts.",
    tracking: {
      category: "Promo CTA",
      action: "Promo CTA button",
      name: "Denoiser MuseHub",
    },
    cta: {
      text: "Get it on MuseHub",
      link: "https://www.musehub.com/plugin/denoiser?utm_source=au-web-banner&utm_medium=au-banner",
    },
  },
  soapVoiceCleanAndCapture: {
    type: "banner",
    isActive: true,
    priority: 50,
    osTargets: ["Windows", "OS X"],
    startDate: "2026-05-14",
    endDate: "2026-05-28",
    message:
      "SOAP Voice Clean & Capture: Professional voice + AI transcription in 2 simple clicks!",
    tracking: {
      category: "Promo CTA",
      action: "Promo CTA button",
      name: "SOAP Voice Clean & Capture MuseHub",
    },
    cta: {
      text: "Get it on MuseHub",
      link: "https://www.musehub.com/bundle/soap-voice-recording-bundle?utm_source=au-web-banner&utm_medium=au-banner",
    },
  },
  speakerDiarizationPro: {
    type: "banner",
    isActive: true,
    priority: 50,
    osTargets: ["Windows", "OS X"],
    startDate: "2026-06-25",
    endDate: "2026-07-09",
    message:
      "Speaker Diarization Pro: The AI tool for splitting multi-speaker audio. Detect, separate, and export voices instantly.",
    tracking: {
      category: "Promo CTA",
      action: "Promo CTA button",
      name: "Speaker Diarization Pro MuseHub",
    },
    cta: {
      text: "Get it on MuseHub",
      link: "https://www.musehub.com/plugin/speaker-diarization-pro?utm_source=au-web-banner&utm_medium=au-banner",
    },
  },
};

export const campaignVideoPromos: Record<string, PromoData> = {
  overtuneStudio: {
    type: "video",
    isActive: true,
    priority: 50,
    slot: 2,
    startDate: "2026-02-18",
    message:
      "Overtune Record your vocals on top of premium beats! Polish, personalize and share with ease",
    tracking: {
      category: "Video embed",
      action: "Watch release video",
      name: "Overtune Studio",
    },
    video: {
      placeholderImage: "https://i.ytimg.com/vi/A4jPvCdbrKA/maxresdefault.jpg",
      imageAltText: "Video thumbnail: Overtune Studio",
      videoURL: "https://www.youtube-nocookie.com/embed/A4jPvCdbrKA?autoplay=1",
    },
    cta: {
      text: "Get it on MuseHub",
      link: "https://www.musehub.com/app/overtune-studio?utm_source=au-web&utm_medium=au-web-video&utm_campaign=au-web-mh-web-overtune-2",
    },
  },
};
