// Generated by "bun run pull-campaigns" — do not edit. Source of truth is the Confluence promo calendar (see .env).
import type { PromoData, TopListCampaign } from "./types";

export const campaignBannerPromos: Record<string, PromoData> = {
  "80sDreamsBundle": {
    type: "banner",
    isActive: true,
    priority: 50,
    osTargets: ["Windows", "OS X"],
    startDate: "2026-06-11",
    endDate: "2026-06-25",
    message:
      "80s Dreams Bundle: The reverb and synth duo for retro-inspired sound. Create lush ambience and vintage tones.",
    tracking: {
      category: "Promo CTA",
      action: "Promo CTA button",
      name: "80s Dreams Bundle MuseHub",
    },
    cta: {
      text: "Get it on MuseHub",
      link: "https://www.musehub.com/bundle/80s-dreams-bundle?utm_source=au-web-banner&utm_medium=au-banner",
    },
  },
  denoiser: {
    type: "banner",
    isActive: true,
    priority: 50,
    osTargets: ["Windows", "OS X"],
    startDate: "2026-05-28",
    endDate: "2026-06-11",
    message:
      "Denoiser: The smart noise removal tool for clean audio. Detect, reduce, and restore sound without artifacts.",
    tracking: {
      category: "Promo CTA",
      action: "Promo CTA button",
      name: "Denoiser MuseHub",
    },
    cta: {
      text: "Get it on MuseHub",
      link: "https://www.musehub.com/plugin/denoiser?utm_source=au-web-banner&utm_medium=au-banner",
    },
  },
  soapVoiceCleanAndCapture: {
    type: "banner",
    isActive: true,
    priority: 50,
    osTargets: ["Windows", "OS X"],
    startDate: "2026-05-14",
    endDate: "2026-05-28",
    message:
      "SOAP Voice Clean & Capture: Professional voice + AI transcription in 2 simple clicks!",
    tracking: {
      category: "Promo CTA",
      action: "Promo CTA button",
      name: "SOAP Voice Clean & Capture MuseHub",
    },
    cta: {
      text: "Get it on MuseHub",
      link: "https://www.musehub.com/bundle/soap-voice-recording-bundle?utm_source=au-web-banner&utm_medium=au-banner",
    },
  },
  speakerDiarizationPro: {
    type: "banner",
    isActive: true,
    priority: 50,
    osTargets: ["Windows", "OS X"],
    startDate: "2026-07-29",
    endDate: "2026-08-13",
    message:
      "Speaker Diarization Pro: The AI tool for splitting multi-speaker audio. Detect, separate, and export voices instantly.",
    tracking: {
      category: "Promo CTA",
      action: "Promo CTA button",
      name: "Speaker Diarization Pro MuseHub",
    },
    cta: {
      text: "Get it on MuseHub",
      link: "https://www.musehub.com/plugin/speaker-diarization-pro?utm_source=au-web-banner-mh-web&utm_medium=speaker-diarization-pro&utm_campaign=au-web-banner-mh-web-speaker-diarization-pro&utm_id=au-web-banner",
    },
  },
  overtune: {
    type: "banner",
    isActive: true,
    priority: 50,
    osTargets: ["Windows", "OS X"],
    startDate: "2026-07-27",
    endDate: "2026-08-10",
    message:
      "Overtune: The beat maker for rappers and singers. Sing, polish, and share.",
    tracking: {
      category: "Promo CTA",
      action: "Promo CTA button",
      name: "Overtune MuseHub",
    },
    cta: {
      text: "Get it on MuseHub",
      link: "https://www.musehub.com/app/overtune-studio?utm_source=au-web-banner-mh-web&utm_medium=overtune-2&utm_campaign=au-web-banner-mh-web-overtune-2r&utm_id=au-web-banner",
    },
  },
  viatorVoiceDenoiser: {
    type: "banner",
    isActive: true,
    priority: 50,
    osTargets: ["Windows", "OS X"],
    startDate: "2026-07-13",
    endDate: "2026-07-27",
    message:
      "Viator Voice Denoiser: The one-knob tool for clean vocals. Remove noise fast and keep your voice natural.",
    tracking: {
      category: "Promo CTA",
      action: "Promo CTA button",
      name: "Viator Voice Denoiser MuseHub",
    },
    cta: {
      text: "Get it on MuseHub",
      link: "https://www.musehub.com/plugin/viator-voice-denoiser?utm_source=au-web-banner-mh-web&utm_medium=viator-voice-denoiser&utm_campaign=au-web-banner-mh-web-viator-voice-denoiser&utm_id=au-web-banner",
    },
  },
  soapVoiceCleaner: {
    type: "banner",
    isActive: true,
    priority: 50,
    osTargets: ["Windows", "OS X"],
    startDate: "2026-08-10",
    endDate: "2026-08-24",
    message:
      "SOAP Voice Cleaner: Professional spoken voice in 3 simple clicks!",
    tracking: {
      category: "Promo CTA",
      action: "Promo CTA button",
      name: "SOAP Voice Cleaner MuseHub",
    },
    cta: {
      text: "Get it on MuseHub",
      link: "https://www.musehub.com/plugin/soap-voice-cleaner?utm_medium=Referral&utm_source=AU&utm_campaign=MH_WW_REF_AU_WEB_ALL_040826_crosslink&utm_content=au_web_banner",
    },
  },
  extract: {
    type: "banner",
    isActive: true,
    priority: 50,
    osTargets: ["Windows", "OS X"],
    startDate: "2026-08-24",
    endDate: "2026-09-07",
    message:
      "Extract:Dialogue 2: The AI tool for dialogue cleanup and restoration. Isolate, control, and refine speech in real time.",
    tracking: {
      category: "Promo CTA",
      action: "Promo CTA button",
      name: "Extract MuseHub",
    },
    cta: {
      text: "Get it on MuseHub",
      link: "https://www.musehub.com/plugin/extractdialogue-2",
    },
  },
};

export const campaignVideoPromos: Record<string, PromoData> = {
  overtuneStudio: {
    type: "video",
    isActive: true,
    priority: 50,
    slot: 2,
    startDate: "2026-02-18",
    message:
      "Overtune: Record your vocals on top of premium beats! Polish, personalize and share with ease",
    tracking: {
      category: "Video embed",
      action: "Watch release video",
      name: "Overtune Studio",
    },
    video: {
      placeholderImage: "https://i.ytimg.com/vi/A4jPvCdbrKA/maxresdefault.jpg",
      imageAltText: "Video thumbnail: Overtune Studio",
      videoURL: "https://www.youtube-nocookie.com/embed/A4jPvCdbrKA?autoplay=1",
    },
    cta: {
      text: "Get it on MuseHub",
      link: "https://www.musehub.com/app/overtune-studio?utm_source=au-web&utm_medium=au-web-video&utm_campaign=au-web-mh-web-overtune-2",
    },
  },
};

export const campaignTopLists: Record<string, TopListCampaign> = {
  topList20261001: {
    items: [
      {
        name: "Soap Voice Clean & Capture Bundle",
        tagline: "Clean up spoken voice and create instant transcripts",
        href: "https://www.musehub.com/bundle/soap-voice-recording-bundle?utm_medium=Referral&utm_source=AU&utm_campaign=MH_WW_REF_AU_WEB_ALL_100926_crosslink&utm_content=top-trending-plugins",
      },
      {
        name: "MuseFX",
        tagline: "Essential collection of mix effects",
        href: "https://www.musehub.com/plugin/musefx?utm_medium=Referral&utm_source=AU&utm_campaign=MH_WW_REF_AU_WEB_ALL_100926_crosslink&utm_content=top-trending-plugins",
      },
      {
        name: "Speaker Splitter Pro",
        tagline: "Automatically split mixed-speaker audio into separate tracks",
        href: "https://www.musehub.com/plugin/speaker-splitter-pro?utm_medium=Referral&utm_source=AU&utm_campaign=MH_WW_REF_AU_WEB_ALL_100926_crosslink&utm_content=top-trending-plugins",
      },
      {
        name: "Trinity EQ",
        tagline: "Shape your sound with precision and warmth",
        href: "https://www.musehub.com/plugin/trinity-eq?utm_medium=Referral&utm_source=AU&utm_campaign=MH_WW_REF_AU_WEB_ALL_100926_crosslink&utm_content=top-trending-plugins",
      },
      {
        name: "Graillon 3",
        tagline: "Real-time vocal tuner",
        href: "https://www.musehub.com/plugin/graillon-3?utm_medium=Referral&utm_source=AU&utm_campaign=MH_WW_REF_AU_WEB_ALL_100926_crosslink&utm_content=top-trending-plugins",
      },
    ],
    startDate: "2026-10-01",
    endDate: "2026-10-29",
  },
};
